sudo: false
language: ruby
rvm:
  - 2.5.8
cache: bundler
before_script:
  - cd spec/dummy && RAILS_ENV=test bundle _1.17.3_ exec rake db:create db:schema:load && cd ../../
script:
  - bundle _1.17.3_ exec rspec spec --color --profile
gemfile:
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x
  - Gemfile-rails-5.2.x
env:
  global:
    BUNDLER_VERSION=1.17.3
notifications:
  email: false
