sudo: false
language: ruby
rvm:
  - 2.1.6
cache: bundler
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec

env:
  - RAILS_VERSION=3.2.22.2
  - RAILS_VERSION=4.0.13
