source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3', '~> 1.3.6'
gem 'protected_attributes'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

gem 'comply', path: '../..'
gem 'jasmine-rails'
gem 'sinon-rails'

group :development, :test do
  gem 'pry-nav'
end
